baseurl: https://cafecolado.netlify.app/
title: VemosDatos
theme: hugo-creative-portfolio-theme
languageCode: en-us
pluralizeListTitles: yes
disqusShortname: ''
googleAnalytics: ''
params:
  copyright: '&copy;2021 Onésimo Galaz'
  description: "Este sitio se comparte información visual, graficas"
  email: onesimogalaz@gmail.com
  navlinks:
    - home: yes
      name: Portafolio
      url: portfolio/
    - name: Sobre mí
      url: about/
    #- name: Get in touch
     # url: contact/
  #  - name: Publicaciones
  #   url: post/      
  sidebarAbout:
    - Es un espacio de difusión para compartir información gráfica mediante la visualización de datos.
    - <i class="fa fa-map-marker"></i> Hermosillo, Sonora, México.
  social:
    #email: email@example.com
    #facebook: full page or profile url in facebook
    #github: full profile url in github
    #gitlab: full profile url in gitlab
    #googleplus: full profile url in googleplus
    #instagram: full profile url in instagram
    #linkedin: full profile url in linkedin
    #stackoverflow: full profile url in stackoverflow
    twitter: https://twitter.com/chxmonesimo
    #whatsapp: wa.me service link
    #youtube: full profile url in youtube
  style: blue

markup:
  goldmark:
    renderer:
      unsafe: true
